# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: DockerApplicationBuild
  displayName: Build API Docker Image
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Docker@2
    inputs:
      command: 'build'
      Dockerfile: 'ProjectRedhead.Application/Dockerfile'
      buildContext: .
      tags: 'projectredhead/api'